### PR TITLE
Add Cedrick Lunven

### PR DESCRIPTION
**Pull request by clun**
Ajout de Cedrick Lunven en tant que speaker avec 2 talks.

### CODE REVIEW

**Review by dadoonet — APPROVED** [review]
It looks good. Could you just rebase on master?

**Comment by clun** [comment]
squashing comments + rebase. Could you confirm this is correct 


```
git remote add brownbaglunch https://github.com/brownbaglunch/bblfr_data.git
git remote -v
git fetch brownbaglunch
git rebase -i HEAD~3
git config --global push.default simple
git push -f
```

**Comment by dadoonet** [comment]
I guess it is.

**Review by dadoonet — APPROVED** [review]

**Comment by dadoonet** [comment]
Welcome! :)

**Comment by clun** [comment]
See you at Snowcamp

**Pull request merged**
