### PR TITLE
Add Clément Poissonnier

### PR DESCRIPTION
**Pull request by cpoissonnier**
I'm not sure why prettier format things that should have been formated by previous PR. If I have to change something, let me know !

### CODE REVIEW

**Comment by dadoonet** [comment]
Yeah. That's weird.
I don't understand though why cities have been modified at the end like that. I don't like this TBH (not your fault).

As I'm not a JS expert, I'd prefer to have @linsolas to review.

**Comment by cpoissonnier** [comment]
No problem, I totally understand !

**Comment by cpoissonnier** [comment]
@linsolas let me know if I have to change something !

**Comment by linsolas** [comment]
Hello,

It's not a JSON file, but a JS file. So not using quotes / double-quotes for keys is perfectly correct when there is no special characters (like for `Clermont-Ferrand`). Some formatters prefers to remove it in fact.
So OK for me (and sorry for the late answer, I missed the notification) on that point - just that the formatter breaks some lines, not a big deal but...

**Pull request merged**
