### PR TITLE
Update Arnaud COURTY sessions + location

### PR DESCRIPTION
**Pull request by Vulcainreo**
Hello,
I would like to update my sessions description and add "La Rochelle" city in location
Thank you in advance for my pull request and for this awesome concept ! 
Regards.
Arnaud.

### CODE REVIEW

**Comment by dadoonet** [comment]
Could you fix the conflict issues?

**Comment by Vulcainreo** [comment]
Yes, sorry for conflicts. It should be fine now.

**Comment by Vulcainreo** [comment]
Hello, after a quick review, my last commit occurs an error on the JSON file.
This part of code is wrong and need to be removed.
```json
    }
  ],
  cities: {
    'Aix-en-Provence': {
      name: 'Aix-en-Provence',
      ville_img: 'img/villes/BBL_Aix-en-provence.png',
      lat: 43.529742,
      lng: 5.447427,
```

Sorry for this mistake and thank you in advance.
Regards.

Arnaud COURTY.

**Comment by dadoonet** [comment]
Could you send a PR to fix it?

**Pull request merged**
