### PR TITLE
Add Guillaume Drouet profile

### PR DESCRIPTION
**Pull request by gdrouet**
Signed-off-by: gdrouet <guidrouet@gmail.com>

### CODE REVIEW

**Comment by dadoonet** [comment]
As I just merged #260 your PR now conflicts. Could you rebase it on master?

**Review by dadoonet — APPROVED** [review]

**Comment by gdrouet** [comment]
Done.

**Review by dadoonet — APPROVED** [review]
Welcome and happy new year! 😉

**Comment by gdrouet** [comment]
Thanks ! Happy new year !

**Pull request merged**
